Text file
aPusio/projekt-grupowy-ZDJAVApol103 pull request #23
Opened 2022-02-26 10:56 UTC by kako80

2022-02-26 10:57 UTC, kam531 approved these changes, later dismissed

2022-02-26 11:00 UTC, lukaszkosecki submitted a review, later dismissed

2022-02-26 12:20 UTC, kam531 submitted a review, later dismissed

2022-02-26 13:28 UTC, aPusio commented
nazwijcie jakos inaczej ten branch bo nawet nie wiem od ktorej gry jest :D

2022-02-26 13:38 UTC, aPusio requested changes

2022-02-26 13:38 UTC, aPusio commented on pom.xml
> +    <maven.compiler.source>17</maven.compiler.source>
nie zmieniajcie tego plz :D

2022-02-26 13:38 UTC, aPusio commented on pom.xml
> +      <artifactId>junit-jupiter-params</artifactId>
testy juz piszecie O.O ? :D

2022-02-26 13:38 UTC, aPusio commented on src/main/java/org/example/Comment.java
> +        Predicate<Paair> haspaair1 = namepaair -> namepaair.equals(new Paair("x", 1));
to na pewno da sie lepiej zrobic :D same kopiuj wklej :D 
jaks Lista ? petla ?

2022-02-26 13:38 UTC, aPusio commented on src/main/java/org/example/Methods.java
> +        switch (number) {
czyli ktos wybiera numer i to odpowiada punktowi w ktory strzela tak ? 
no to tutaj 2 sugestie :D 
1. Zrobice klase Point ktora trzyma x i y :D 
2. jak zrobicie Mape albo Enum ktory trzyma to ze 1 -> [0][0] to bedziecie mogli latwo z tego korzystac i latwo rozszerzac gre i zniknie wam ten caly switch tylko wystarczy mag.get(1) ktore zwroci Point 0,0

2022-02-26 13:38 UTC, aPusio commented on src/main/java/org/example/Methods.java
> +        boolean b = false;
to mi sie nie podoba :D co to jest b i czemu trzeba uzywac break :D to robi zwykly equals z listy nie ? to moze jakis stream.findFirst czy cos :D?

2022-02-26 13:38 UTC, aPusio commented on src/main/java/org/example/Methods.java
> +            case 1 : {
znowu kopiuj wklej i ten sam swithc ktory da sie skrocic :D

2022-02-26 13:38 UTC, aPusio commented on src/main/java/org/example/Methods.java
> +        Predicate<Paair> haspaair1 = namepaair -> namepaair.equals(new Paair("x", 1));
sporo tego kopiowania

2022-02-26 13:38 UTC, aPusio commented on src/main/java/org/example/Paair.java
> +public class Paair {
mozna lombokiem :D

2022-02-26 13:38 UTC, aPusio commented on src/main/java/org/example/PlayerOne.java
> +    String x;
x?

2022-02-26 13:38 UTC, aPusio commented on src/main/java/org/example/TicTacToe.java
> +        List<Paair> listPaair = new ArrayList<>();
duzo sie tu dzieje, dacie rade to chociaz podzielic na funkcje ?

2022-02-26 13:38 UTC, aPusio commented on src/main/java/org/example/TicTacToe.java
> +        List<Paair> listPaair = new ArrayList<>();
to tak naprawde startuje gre wiec to tez nie moze zostac w mainie, w prawdziwym mainie wspolnym dla wszystkich powinno byc tylko jedno wywolanie jakiegos obiektu ktory wystartuje gre

2022-02-28 06:09 UTC, aPusio commented
1. macie konflitky i zeby sie zmergowac misicie je rozwiazac :D 
2. nie mysleliscie zeby zaczac od nowa jezeli nie panujecie nad tym potworkiem :D albo wyciac czesci ktorych nie rozumiecie / nie lubicie ?

2022-03-04 17:21 UTC, closed without merging